export const weatherCondition: Record<string, number> = {
  Sunny: 0.75,
  Clear: 1,
  'Partly cloudy': 1,
  Cloudy: 1,
  Overcast: 0.85,
  Mist: 0.75,
  'Patchy rain possible': 0.75,
  'Patchy snow possible': 0.75,
  'Patchy sleet possible': 0.75,
  'Patchy freezing drizzle possible': 0.5,
  'Thundery outbreaks possible': 0.45,
  'Blowing snow': 0.45,
  Blizzard: 0.1,
  Fog: 0.2,
  'Freezing fog': 0.2,
  'Patchy light drizzle': 0.75,
  'Light drizzle': 0.65,
  'Freezing drizzle': 0.45,
  'Heavy freezing drizzle': 0.1,
  'Patchy light rain': 0.65,
  'Light rain': 0.4,
  'Moderate rain at times': 0.3,
  'Moderate rain': 0.3,
  'Heavy rain at times': 0.1,
  'Heavy rain': 0.1,
  'Light freezing rain': 0.3,
  'Moderate or heavy freezing rain': 0.2,
  'Light sleet': 0.65,
  'Moderate or heavy sleet': 0.45,
  'Patchy light snow': 0.85,
  'Light snow': 0.65,
  'Patchy moderate snow': 0.65,
  'Moderate snow': 0.45,
  'Patchy heavy snow': 0.15,
  'Heavy snow': 0.1,
  'Ice pellets': 0.1,
  'Light rain shower': 0.45,
  'Moderate or heavy rain shower': 0.3,
  'Torrential rain shower': 0.1,
  'Light sleet showers': 0.1,
  'Moderate or heavy sleet showers': 0.1,
  'Light snow showers': 0.35,
  'Moderate or heavy snow showers': 0.15,
  'Light showers of ice pellets': 0.15,
  'Moderate or heavy showers of ice pellets': 0.15,
  'Patchy light rain with thunder': 0.15,
  'Moderate or heavy rain with thunder': 0.15,
  'Patchy light snow with thunder': 0.15,
  'Moderate or heavy snow with thunder': 0.15,
};
