export const goodWeather: string[] = [
  'Sunny',
  'Clear',
  'Partly cloudy',
  'Cloudy',
  'Overcast',
  'Mist',
];

export const moderateWeather: string[] = [
  'Patchy rain possible',
  'Patchy snow possible',
  'Patchy sleet possible',
  'Patchy freezing drizzle possible',
  'Patchy light drizzle',
  'Light drizzle',
  'Patchy light rain',
  'Light rain',
  'Moderate rain at times',
  'Moderate rain',
  'Light sleet',
  'Patchy light snow',
  'Light snow',
  'Patchy moderate snow',
  'Moderate snow',
  'Light rain shower',
  'Light sleet showers',
  'Light snow showers',
];

export const badWeather: string[] = [
  'Thundery outbreaks possible',
  'Blowing snow',
  'Blizzard',
  'Fog',
  'Freezing fog',
  'Freezing drizzle',
  'Heavy freezing drizzle',
  'Heavy rain at times',
  'Heavy rain',
  'Light freezing rain',
  'Moderate or heavy freezing rain',
  'Moderate or heavy sleet',
  'Patchy heavy snow',
  'Heavy snow',
  'Ice pellets',
  'Moderate or heavy rain shower',
  'Torrential rain shower',
  'Moderate or heavy sleet showers',
  'Moderate or heavy snow showers',
  'Light showers of ice pellets',
  'Moderate or heavy showers of ice pellets',
  'Patchy light rain with thunder',
  'Moderate or heavy rain with thunder',
  'Patchy light snow with thunder',
  'Moderate or heavy snow with thunder',
];
